#!/usr/bin/env python3
"""Scaffold a new ADK agentic workflow project.

Usage:
    python init_adk_workflow.py --type graph --lang python --name my-flow
    python init_adk_workflow.py --type dynamic --lang go --name order-pipeline
    python init_adk_workflow.py --type collaborative --lang python --name support-triage

Workflow types:
    graph           - DAG-based workflow (Node + Edge + Condition)
    dynamic         - Programmatic workflow (Python/Go code drives flow)
    collaborative   - Coordinator + sub-agent delegation
    template-seq    - SequentialAgent pipeline
    template-parallel - ParallelAgent fan-out
"""

import argparse
import os
import sys
from pathlib import Path

TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "assets" / "workflow-templates"

WORKFLOW_TYPES = {
    "graph": "DAG-based workflow with nodes, edges, and conditions",
    "dynamic": "Programmatic workflow with imperative control flow",
    "collaborative": "Coordinator agent delegating to sub-agents",
    "template-seq": "SequentialAgent linear pipeline",
    "template-parallel": "ParallelAgent fan-out pattern",
    "template-loop": "LoopAgent iterative refinement with quality gate",
}

PYTHON_TEMPLATE = """# {name} — {wf_type} workflow
# Generated by adk-agentic-prod-workflows

{imports}

# ── Agent definitions ──────────────────────────────────────────────

{agents}

# ── Tool definitions ───────────────────────────────────────────────

{tools}

# ── Workflow assembly ──────────────────────────────────────────────

{workflow}

# ── Entrypoint ─────────────────────────────────────────────────────

{entrypoint}
"""

GO_TEMPLATE = """// {name} — {wf_type} workflow
// Generated by adk-agentic-prod-workflows

package main

import (
{imports}
)

// ── Agent definitions ─────────────────────────────────────────────

{agents}

// ── Tool definitions ──────────────────────────────────────────────

{tools}

// ── Workflow assembly ─────────────────────────────────────────────

{workflow}

// ── Entrypoint ──────────────────────────────────────────────────

{entrypoint}
"""


def generate_graph_python(name: str) -> dict:
    imports = """from google.adk import Agent
from google.adk.agents.graph import GraphAgent, Node, Edge, Condition
from google.adk.tools import FunctionTool
from pydantic import BaseModel, Field
import structlog

logger = structlog.get_logger(__name__)"""

    agents = f"""class ValidateInput(BaseModel):
    query: str = Field(description="User query to validate")

class ValidateOutput(BaseModel):
    is_valid: bool
    sanitized_query: str
    reason: str | None = None

def validate_input(params: ValidateInput) -> ValidateOutput:
    logger.info("validate_input", query_length=len(params.query))
    if len(params.query) < 3:
        return ValidateOutput(is_valid=False, sanitized_query="", reason="Query too short")
    return ValidateOutput(is_valid=True, sanitized_query=params.query.strip(), reason=None)

class ProcessInput(BaseModel):
    query: str = Field(description="Sanitized query to process")

class ProcessOutput(BaseModel):
    result: str
    confidence: float

def process_query(params: ProcessInput) -> ProcessOutput:
    logger.info("process_query", query=params.query)
    return ProcessOutput(result=f"Processed: {{params.query}}", confidence=0.95)

validator_agent = Agent(
    name="{name}_validator",
    model="gemini-2.5-flash",
    instruction="Validate and sanitize user input before processing.",
    tools=[FunctionTool(validate_input)],
)

processor_agent = Agent(
    name="{name}_processor",
    model="gemini-2.5-flash",
    instruction="Process validated queries and return structured results.",
    tools=[FunctionTool(process_query)],
)"""

    workflow = f"""graph_agent = GraphAgent(
    name="{name}_graph",
    nodes=[
        Node(id="validate", agent=validator_agent),
        Node(id="process", agent=processor_agent),
        Node(id="reject", agent=Agent(
            name="reject_handler",
            model="gemini-2.5-flash",
            instruction="Tell the user their input was invalid and suggest fixes.",
        )),
    ],
    edges=[
        Edge(source="validate", target="process", condition=Condition(
            lambda state: state.get("is_valid", False)
        )),
        Edge(source="validate", target="reject", condition=Condition(
            lambda state: not state.get("is_valid", False)
        )),
    ],
    entry_point="validate",
)"""

    entrypoint = """if __name__ == "__main__":
    import asyncio
    from google.adk.runners import InProcessRunner

    async def main():
        runner = InProcessRunner(agent=graph_agent)
        result = await runner.run(query="Test query")
        print(f"Result: {result}")

    asyncio.run(main())"""

    return {"imports": imports, "agents": agents, "tools": "", "workflow": workflow, "entrypoint": entrypoint}


def generate_dynamic_python(name: str) -> dict:
    imports = """from google.adk import Agent
from google.adk.tools import FunctionTool
from pydantic import BaseModel, Field
import structlog

logger = structlog.get_logger(__name__)"""

    agents = f"""class FetchDataInput(BaseModel):
    source: str = Field(description="Data source identifier")

class FetchDataOutput(BaseModel):
    data: list[dict]
    count: int

def fetch_data(params: FetchDataInput) -> FetchDataOutput:
    logger.info("fetch_data", source=params.source)
    return FetchDataOutput(data=[], count=0)

class TransformDataInput(BaseModel):
    data: list[dict] = Field(description="Raw data to transform")
    operation: str = Field(description="Transform operation name")

class TransformDataOutput(BaseModel):
    transformed: list[dict]
    stats: dict

def transform_data(params: TransformDataInput) -> TransformDataOutput:
    logger.info("transform_data", operation=params.operation)
    return TransformDataOutput(transformed=[], stats={{}})

fetch_agent = Agent(
    name="{name}_fetcher",
    model="gemini-2.5-flash",
    instruction="Fetch data from specified sources using the fetch_data tool.",
    tools=[FunctionTool(fetch_data)],
)

transform_agent = Agent(
    name="{name}_transformer",
    model="gemini-2.5-flash",
    instruction="Transform raw data using the transform_data tool.",
    tools=[FunctionTool(transform_data)],
)"""

    workflow = f"""class {name.replace('-', '_').title()}Workflow:
    def __init__(self):
        self.fetch_agent = fetch_agent
        self.transform_agent = transform_agent
        self.state: dict = {{}}

    async def run(self, query: str) -> dict:
        self.state["correlation_id"] = f"wf_{{id(self)}}"

        logger.info("workflow_start", correlation_id=self.state["correlation_id"])

        fetch_result = await self._run_agent(self.fetch_agent, query)
        if fetch_result.get("error"):
            return {{"status": "error", "error": fetch_result["error"]}}

        self.state["raw_data"] = fetch_result.get("data", [])
        self.state["count"] = fetch_result.get("count", 0)

        transform_result = await self._run_agent(
            self.transform_agent,
            f"Transform {{self.state['count']}} records"
        )
        self.state["transformed"] = transform_result.get("transformed", [])

        logger.info("workflow_complete", correlation_id=self.state["correlation_id"])
        return {{"status": "ok", "data": self.state["transformed"]}}

    async def _run_agent(self, agent, query: str) -> dict:
        from google.adk.runners import InProcessRunner
        runner = InProcessRunner(agent=agent)
        result = await runner.run(query=query)
        return result"""

    entrypoint = """if __name__ == "__main__":
    import asyncio

    async def main():
        wf = {class_name}Workflow()
        result = await wf.run("Fetch and transform sales data")
        print(f"Result: {result}")

    asyncio.run(main())""".format(class_name=name.replace('-', '_').title())

    return {"imports": imports, "agents": agents, "tools": "", "workflow": workflow, "entrypoint": entrypoint}


def generate_collaborative_python(name: str) -> dict:
    imports = """from google.adk import Agent
from google.adk.tools import FunctionTool
from pydantic import BaseModel, Field
import structlog

logger = structlog.get_logger(__name__)"""

    agents = f"""class ResearchInput(BaseModel):
    topic: str = Field(description="Research topic")

class ResearchOutput(BaseModel):
    findings: list[str]
    sources: list[str]

def research_topic(params: ResearchInput) -> ResearchOutput:
    logger.info("research_topic", topic=params.topic)
    return ResearchOutput(findings=[], sources=[])

class CodeInput(BaseModel):
    spec: str = Field(description="Implementation specification")

class CodeOutput(BaseModel):
    code: str
    language: str
    tests: str

def write_code(params: CodeInput) -> CodeOutput:
    logger.info("write_code", spec=params.spec[:100])
    return CodeOutput(code="", language="python", tests="")

class ReviewInput(BaseModel):
    code: str = Field(description="Code to review")

class ReviewOutput(BaseModel):
    approved: bool
    issues: list[str]

def review_code(params: ReviewInput) -> ReviewOutput:
    logger.info("review_code", code_length=len(params.code))
    return ReviewOutput(approved=True, issues=[])

researcher = Agent(
    name="{name}_researcher",
    model="gemini-2.5-flash",
    instruction="Research topics thoroughly using the research_topic tool.",
    tools=[FunctionTool(research_topic)],
)

coder = Agent(
    name="{name}_coder",
    model="gemini-2.5-pro",
    instruction="Write production code based on specifications.",
    tools=[FunctionTool(write_code)],
)

reviewer = Agent(
    name="{name}_reviewer",
    model="gemini-2.5-flash",
    instruction="Review code for correctness and quality.",
    tools=[FunctionTool(review_code)],
)

coordinator = Agent(
    name="{name}_coordinator",
    model="gemini-2.5-pro",
    instruction=f\"\"\"You are a task coordinator for the {name} workflow.
    1. Analyze the user's goal
    2. Delegate research to {{name}}_researcher
    3. Delegate implementation to {{name}}_coder
    4. Delegate review to {{name}}_reviewer
    5. Track progress in session.state["plan"]
    6. Do not execute tasks yourself — always delegate to sub-agents.
    Max delegation depth: 3.\"\"\",
    sub_agents=[researcher, coder, reviewer],
)"""

    workflow = f"""# Coordinator agent IS the workflow entry point.
# Sub-agents execute delegated tasks.
# State flows through coordinator's session.state.

__all__ = ["coordinator", "researcher", "coder", "reviewer"]"""

    entrypoint = """if __name__ == "__main__":
    import asyncio
    from google.adk.runners import InProcessRunner

    async def main():
        runner = InProcessRunner(agent=coordinator)
        result = await runner.run(query="Build a REST API for user management")
        print(f"Result: {result}")

    asyncio.run(main())"""

    return {"imports": imports, "agents": agents, "tools": "", "workflow": workflow, "entrypoint": entrypoint}


def generate_template_seq_python(name: str) -> dict:
    imports = """from google.adk import Agent
from google.adk.agents import SequentialAgent
from google.adk.tools import FunctionTool
from pydantic import BaseModel, Field
import structlog

logger = structlog.get_logger(__name__)"""

    agents = f"""class StepInput(BaseModel):
    data: dict = Field(description="Input data for this step")

class StepOutput(BaseModel):
    data: dict
    status: str

def step_one(params: StepInput) -> StepOutput:
    logger.info("step_one")
    return StepOutput(data=params.data, status="ok")

def step_two(params: StepInput) -> StepOutput:
    logger.info("step_two")
    return StepOutput(data=params.data, status="ok")

def step_three(params: StepInput) -> StepOutput:
    logger.info("step_three")
    return StepOutput(data=params.data, status="ok")

agent_one = Agent(
    name="{name}_step_one",
    model="gemini-2.5-flash",
    instruction="Execute step 1 of the pipeline.",
    tools=[FunctionTool(step_one)],
)

agent_two = Agent(
    name="{name}_step_two",
    model="gemini-2.5-flash",
    instruction="Execute step 2 of the pipeline.",
    tools=[FunctionTool(step_two)],
)

agent_three = Agent(
    name="{name}_step_three",
    model="gemini-2.5-flash",
    instruction="Execute step 3 of the pipeline.",
    tools=[FunctionTool(step_three)],
)"""

    workflow = f"""pipeline = SequentialAgent(
    name="{name}_pipeline",
    sub_agents=[agent_one, agent_two, agent_three],
)"""

    entrypoint = """if __name__ == "__main__":
    import asyncio
    from google.adk.runners import InProcessRunner

    async def main():
        runner = InProcessRunner(agent=pipeline)
        result = await runner.run(query="Execute the pipeline")
        print(f"Result: {result}")

    asyncio.run(main())"""

    return {"imports": imports, "agents": agents, "tools": "", "workflow": workflow, "entrypoint": entrypoint}


def generate_template_parallel_python(name: str) -> dict:
    imports = """from google.adk import Agent
from google.adk.agents import ParallelAgent
from google.adk.tools import FunctionTool
from pydantic import BaseModel, Field
import structlog

logger = structlog.get_logger(__name__)"""

    agents = f"""class TaskInput(BaseModel):
    chunk: dict = Field(description="Data chunk to process")
    worker_id: str = Field(description="Worker identifier")

class TaskOutput(BaseModel):
    result: dict
    worker_id: str

def process_chunk(params: TaskInput) -> TaskOutput:
    logger.info("process_chunk", worker_id=params.worker_id)
    return TaskOutput(result=params.chunk, worker_id=params.worker_id)

worker_a = Agent(
    name="{name}_worker_a",
    model="gemini-2.5-flash",
    instruction="Process data chunks assigned to Worker A.",
    tools=[FunctionTool(process_chunk)],
)

worker_b = Agent(
    name="{name}_worker_b",
    model="gemini-2.5-flash",
    instruction="Process data chunks assigned to Worker B.",
    tools=[FunctionTool(process_chunk)],
)

worker_c = Agent(
    name="{name}_worker_c",
    model="gemini-2.5-flash",
    instruction="Process data chunks assigned to Worker C.",
    tools=[FunctionTool(process_chunk)],
)"""

    workflow = f"""fan_out = ParallelAgent(
    name="{name}_fan_out",
    sub_agents=[worker_a, worker_b, worker_c],
)"""

    entrypoint = """if __name__ == "__main__":
    import asyncio
    from google.adk.runners import InProcessRunner

    async def main():
        runner = InProcessRunner(agent=fan_out)
        result = await runner.run(query="Process all data chunks in parallel")
        print(f"Result: {result}")

    asyncio.run(main())"""

    return {"imports": imports, "agents": agents, "tools": "", "workflow": workflow, "entrypoint": entrypoint}


def generate_template_loop_python(name: str) -> dict:
    imports = """from google.adk import Agent
from google.adk.agents import LoopAgent
from google.adk.tools import FunctionTool
from google.adk.tools.base import ToolContext
from pydantic import BaseModel, Field
import structlog

logger = structlog.get_logger(__name__)"""

    agents = f"""class GenerateInput(BaseModel):
    task: str = Field(description="Task to generate output for")

class GenerateOutput(BaseModel):
    content: str
    confidence: float

def generate_content(params: GenerateInput) -> GenerateOutput:
    logger.info("generate_content", task=params.task[:100])
    return GenerateOutput(content=f"Draft for: {{params.task}}", confidence=0.7)

def exit_loop(tool_context: ToolContext) -> dict:
    \"\"\"Signal loop to exit — quality gate passed.\"\"\"
    tool_context.actions.escalate = True
    return {{"status": "exit", "reason": "quality_gate_passed"}}

class ReviewInput(BaseModel):
    content: str = Field(description="Content to review")
    criteria: list[str] = Field(description="Quality criteria")

class ReviewOutput(BaseModel):
    score: float = Field(ge=0.0, le=1.0)
    issues: list[str]
    passed: bool

def review_content(params: ReviewInput) -> ReviewOutput:
    logger.info("review_content", content_length=len(params.content))
    # Quality scoring against criteria
    score = 0.85  # Placeholder — real scoring logic here
    return ReviewOutput(
        score=score,
        issues=[] if score >= 0.8 else ["Needs improvement"],
        passed=score >= 0.8,
    )

generator = Agent(
    name="{name}_generator",
    model="gemini-2.5-flash",
    instruction="Generate content based on the task. Use generate_content tool.",
    tools=[FunctionTool(generate_content)],
)

reviewer = Agent(
    name="{name}_reviewer",
    model="gemini-2.5-flash",
    instruction="Review generated content against quality criteria. Score 0-1. "
                "If score >= 0.8, call exit_loop. Otherwise provide specific feedback.",
    tools=[FunctionTool(review_content), FunctionTool(exit_loop)],
)"""

    workflow = f"""refinement_loop = LoopAgent(
    name="{name}_loop",
    sub_agents=[generator, reviewer],
    max_iterations=5,
)

# Quality gate: reviewer calls exit_loop() when score >= 0.8
# Loop exits early if quality gate passes, or after max_iterations"""

    entrypoint = """if __name__ == "__main__":
    import asyncio
    from google.adk.runners import InProcessRunner

    async def main():
        runner = InProcessRunner(agent=refinement_loop)
        result = await runner.run(query="Generate and refine a report on Q4 metrics")
        print(f"Result: {result}")

    asyncio.run(main())"""

    return {"imports": imports, "agents": agents, "tools": "", "workflow": workflow, "entrypoint": entrypoint}


PYTHON_GENERATORS = {
    "graph": generate_graph_python,
    "dynamic": generate_dynamic_python,
    "collaborative": generate_collaborative_python,
    "template-seq": generate_template_seq_python,
    "template-parallel": generate_template_parallel_python,
    "template-loop": generate_template_loop_python,
}


def generate_go_graph(name: str) -> dict:
    safe_name = name.replace("-", "_")
    imports = '''\t"context"
\t"fmt"
\t"log/slog"
\t"os"'''

    agents = f"""type {safe_name.title()}Agent struct {{
    name string
}}

func New{safe_name.title()}Agent(name string) *{safe_name.title()}Agent {{
    return &{safe_name.title()}Agent{{name: name}}
}}

func (a *{safe_name.title()}Agent) Run(ctx context.Context, input string) (string, error) {{
    slog.Info("agent run", "agent", a.name, "input", input)
    return fmt.Sprintf("Processed: %s", input), nil
}}"""

    tools = """type ToolContext struct {
    ToolName string
}

func executeTool(ctx ToolContext, params map[string]any) (map[string]any, error) {
    slog.Info("tool executed", "tool", ctx.ToolName)
    return map[string]any{"status": "ok"}, nil
}"""

    workflow = f"""type WorkflowNode struct {{
    ID    string
    Agent *{safe_name.title()}Agent
}}

type WorkflowEdge struct {{
    Source    string
    Target    string
    Condition func(state map[string]any) bool
}}

type {safe_name.title()}Workflow struct {{
    Nodes      []WorkflowNode
    Edges      []WorkflowEdge
    EntryPoint string
    State      map[string]any
}}

func New{safe_name.title()}Workflow() *{safe_name.title()}Workflow {{
    validateAgent := New{safe_name.title()}Agent("{name}_validator")
    processAgent := New{safe_name.title()}Agent("{name}_processor")

    return &{safe_name.title()}Workflow{{
        Nodes: []WorkflowNode{{
            {{ID: "validate", Agent: validateAgent}},
            {{ID: "process", Agent: processAgent}},
        }},
        Edges: []WorkflowEdge{{
            {{Source: "validate", Target: "process"}},
        }},
        EntryPoint: "validate",
        State:      make(map[string]any),
    }}
}}

func (w *{safe_name.title()}Workflow) Run(ctx context.Context, query string) error {{
    slog.Info("workflow start", "correlation_id", fmt.Sprintf("wf_%p", w))

    currentNodeID := w.EntryPoint
    for currentNodeID != "" {{
        node := w.findNode(currentNodeID)
        if node == nil {{
            return fmt.Errorf("node not found: %s", currentNodeID)
        }}

        result, err := node.Agent.Run(ctx, query)
        if err != nil {{
            return fmt.Errorf("node %s error: %w", currentNodeID, err)
        }}

        w.State[currentNodeID+"_result"] = result
        currentNodeID = w.nextNode(currentNodeID)
    }}

    slog.Info("workflow complete")
    return nil
}}

func (w *{safe_name.title()}Workflow) findNode(id string) *WorkflowNode {{
    for i := range w.Nodes {{
        if w.Nodes[i].ID == id {{
            return &w.Nodes[i]
        }}
    }}
    return nil
}}

func (w *{safe_name.title()}Workflow) nextNode(currentID string) string {{
    for _, edge := range w.Edges {{
        if edge.Source == currentID {{
            if edge.Condition == nil || edge.Condition(w.State) {{
                return edge.Target
            }}
        }}
    }}
    return ""
}}"""

    entrypoint = f"""func main() {{
    ctx := context.Background()

    wf := New{safe_name.title()}Workflow()
    if err := wf.Run(ctx, "Test query"); err != nil {{
        slog.Error("workflow failed", "error", err)
        os.Exit(1)
    }}

    fmt.Println("Workflow completed successfully")
}}"""

    return {"imports": imports, "agents": agents, "tools": tools, "workflow": workflow, "entrypoint": entrypoint}


def generate_go_dynamic(name: str) -> dict:
    safe_name = name.replace("-", "_")
    imports = '''\t"context"
\t"fmt"
\t"log/slog"
\t"os"'''

    agents = f"""type Agent interface {{
    Name() string
    Run(ctx context.Context, input string) (string, error)
}}

type BaseAgent struct {{
    name string
}}

func (a *BaseAgent) Name() string {{ return a.name }}

type FetcherAgent struct {{
    BaseAgent
}}

func NewFetcherAgent(name string) *FetcherAgent {{
    return &FetcherAgent{{BaseAgent{{name: name}}}}
}}

func (a *FetcherAgent) Run(ctx context.Context, input string) (string, error) {{
    slog.Info("fetching", "agent", a.name, "input", input)
    return fmt.Sprintf("Fetched: %s", input), nil
}}

type TransformerAgent struct {{
    BaseAgent
}}

func NewTransformerAgent(name string) *TransformerAgent {{
    return &TransformerAgent{{BaseAgent{{name: name}}}}
}}

func (a *TransformerAgent) Run(ctx context.Context, input string) (string, error) {{
    slog.Info("transforming", "agent", a.name, "input", input)
    return fmt.Sprintf("Transformed: %s", input), nil
}}"""

    tools = """type Tool interface {
    Execute(params map[string]any) (map[string]any, error)
}

type FetchDataTool struct{}

func (t *FetchDataTool) Execute(params map[string]any) (map[string]any, error) {
    slog.Info("fetch_data", "params", params)
    return map[string]any{"data": []string{}, "status": "ok"}, nil
}

type TransformTool struct{}

func (t *TransformTool) Execute(params map[string]any) (map[string]any, error) {
    slog.Info("transform", "params", params)
    return map[string]any{"transformed": []string{}, "status": "ok"}, nil
}"""

    workflow = f"""type {safe_name.title()}Workflow struct {{
    CorrelID string
    Agents   []Agent
    State    map[string]any
}}

func New{safe_name.title()}Workflow() *{safe_name.title()}Workflow {{
    return &{safe_name.title()}Workflow{{
        CorrelID: fmt.Sprintf("wf_%d", os.Getpid()),
        Agents: []Agent{{
            NewFetcherAgent("{name}_fetcher"),
            NewTransformerAgent("{name}_transformer"),
        }},
        State: make(map[string]any),
    }}
}}

func (w *{safe_name.title()}Workflow) Run(ctx context.Context, query string) error {{
    slog.Info("workflow start", "correlation_id", w.CorrelID)

    for _, agent := range w.Agents {{
        result, err := agent.Run(ctx, query)
        if err != nil {{
            slog.Error("agent failed", "agent", agent.Name(), "error", err)
            return fmt.Errorf("agent %s failed: %w", agent.Name(), err)
        }}
        w.State[agent.Name()] = result
        query = result  // Pass output to next agent
    }}

    slog.Info("workflow complete", "correlation_id", w.CorrelID)
    return nil
}}"""

    entrypoint = f"""func main() {{
    ctx := context.Background()

    wf := New{safe_name.title()}Workflow()
    if err := wf.Run(ctx, "Process data pipeline"); err != nil {{
        slog.Error("workflow failed", "error", err)
        os.Exit(1)
    }}

    fmt.Println("Workflow completed successfully")
    fmt.Printf("State: %v\\n", wf.State)
}}"""

    return {"imports": imports, "agents": agents, "tools": tools, "workflow": workflow, "entrypoint": entrypoint}


def generate_go_collaborative(name: str) -> dict:
    safe_name = name.replace("-", "_")
    imports = '''\t"context"
\t"fmt"
\t"log/slog"
\t"os"
\t"sync"'''

    agents = f"""type SharedState struct {{
    mu    sync.RWMutex
    State map[string]string
}}

func NewSharedState() *SharedState {{
    return &SharedState{{State: make(map[string]string)}}
}}

func (s *SharedState) Set(key, value string) {{
    s.mu.Lock()
    defer s.mu.Unlock()
    s.State[key] = value
}}

func (s *SharedState) Get(key string) string {{
    s.mu.RLock()
    defer s.mu.RUnlock()
    return s.State[key]
}}

type CoordinatedAgent struct {{
    name  string
    state *SharedState
}}

func NewCoordinatedAgent(name string, state *SharedState) *CoordinatedAgent {{
    return &CoordinatedAgent{{name: name, state: state}}
}}

func (a *CoordinatedAgent) Run(ctx context.Context, input string) (string, error) {{
    slog.Info("agent running", "agent", a.name)
    result := fmt.Sprintf("[%s]: %s", a.name, input)
    a.state.Set(a.name, result)
    return result, nil
}}

func (a *CoordinatedAgent) Name() string {{ return a.name }}"""

    tools = """type SharedTool struct {
    name string
}

func (t *SharedTool) Execute(ctx context.Context, params map[string]any) (map[string]any, error) {
    slog.Info("shared tool execute", "tool", t.name, "params", params)
    return map[string]any{"status": "ok"}, nil
}"""

    workflow = f"""type {safe_name.title()}Coordinator struct {{
    State   *SharedState
    Agents  []*CoordinatedAgent
}}

func New{safe_name.title()}Coordinator() *{safe_name.title()}Coordinator {{
    state := NewSharedState()
    return &{safe_name.title()}Coordinator{{
        State: state,
        Agents: []*CoordinatedAgent{{
            NewCoordinatedAgent("{name}_researcher", state),
            NewCoordinatedAgent("{name}_writer", state),
            NewCoordinatedAgent("{name}_reviewer", state),
        }},
    }}
}}

func (c *{safe_name.title()}Coordinator) Run(ctx context.Context, query string) error {{
    slog.Info("coordinator start", "correlation_id", fmt.Sprintf("wf_%p", c))

    // Coordinator delegates to each agent, they share state
    for _, agent := range c.Agents {{
        result, err := agent.Run(ctx, query)
        if err != nil {{
            slog.Error("agent failed", "agent", agent.Name(), "error", err)
            return err
        }}
        slog.Info("agent completed", "agent", agent.Name(), "result", result)
    }}

    slog.Info("coordinator complete", "shared_state", c.State.State)
    return nil
}}"""

    entrypoint = f"""func main() {{
    ctx := context.Background()

    coord := New{safe_name.title()}Coordinator()
    if err := coord.Run(ctx, "Research and document the API design"); err != nil {{
        slog.Error("coordinator failed", "error", err)
        os.Exit(1)
    }}

    fmt.Println("Coordinator workflow completed")
}}"""

    return {"imports": imports, "agents": agents, "tools": tools, "workflow": workflow, "entrypoint": entrypoint}


def generate_go_template_sequential(name: str) -> dict:
    safe_name = name.replace("-", "_")
    imports = '''\t"context"
\t"fmt"
\t"log/slog"
\t"os"'''

    agents = f"""type SeqAgent struct {{
    name string
}}

func (a *SeqAgent) Name() string {{ return a.name }}

func (a *SeqAgent) Run(ctx context.Context, input string) (string, error) {{
    slog.Info("sequential step", "agent", a.name, "input", input[:80])
    return fmt.Sprintf("[%s output]: %s", a.name, input), nil
}}"""

    tools = """// Sequential pipeline passes output → input between agents.
// Each agent transforms the data before passing to the next.
// No shared tool needed for simple pipelines."""

    workflow = f"""type {safe_name.title()}Pipeline struct {{
    Agents []*SeqAgent
}}

func New{safe_name.title()}Pipeline() *{safe_name.title()}Pipeline {{
    return &{safe_name.title()}Pipeline{{
        Agents: []*SeqAgent{{
            {{name: "{name}_writer"}},
            {{name: "{name}_reviewer"}},
            {{name: "{name}_publisher"}},
        }},
    }}
}}

func (p *{safe_name.title()}Pipeline) Run(ctx context.Context, query string) error {{
    slog.Info("pipeline start", "correlation_id", fmt.Sprintf("wf_%p", p))
    current := query

    for _, agent := range p.Agents {{
        result, err := agent.Run(ctx, current)
        if err != nil {{
            return fmt.Errorf("step %s failed: %w", agent.Name(), err)
        }}
        current = result  // Output of step N = input of step N+1
    }}

    slog.Info("pipeline complete", "final_output", current)
    fmt.Println("Final output:", current)
    return nil
}}"""

    entrypoint = f"""func main() {{
    ctx := context.Background()

    pipeline := New{safe_name.title()}Pipeline()
    if err := pipeline.Run(ctx, "Write a technical blog post about Go"); err != nil {{
        slog.Error("pipeline failed", "error", err)
        os.Exit(1)
    }}

    fmt.Println("Sequential pipeline completed")
}}"""

    return {"imports": imports, "agents": agents, "tools": tools, "workflow": workflow, "entrypoint": entrypoint}


def generate_go_template_parallel(name: str) -> dict:
    safe_name = name.replace("-", "_")
    imports = '''\t"context"
\t"fmt"
\t"log/slog"
\t"os"
\t"sync"'''

    agents = f"""type ParallelWorker struct {{
    name string
}}

func (w *ParallelWorker) Name() string {{ return w.name }}

func (w *ParallelWorker) Run(ctx context.Context, input string) (string, error) {{
    slog.Info("worker running", "worker", w.name, "input", input[:80])
    return fmt.Sprintf("[%s]: %s", w.name, input), nil
}}"""

    tools = """// Parallel workers run independently. Each worker has its own tool set.
// Results are aggregated after all workers complete."""

    workflow = f"""type {safe_name.title()}FanOut struct {{
    Workers []*ParallelWorker
}}

func New{safe_name.title()}FanOut() *{safe_name.title()}FanOut {{
    return &{safe_name.title()}FanOut{{
        Workers: []*ParallelWorker{{
            {{name: "{name}_web_search"}},
            {{name: "{name}_db_query"}},
            {{name: "{name}_api_call"}},
        }},
    }}
}}

func (f *{safe_name.title()}FanOut) Run(ctx context.Context, query string) (map[string]string, error) {{
    slog.Info("fan_out start", "correlation_id", fmt.Sprintf("wf_%p", f), "workers", len(f.Workers))

    var wg sync.WaitGroup
    results := make(map[string]string)
    var mu sync.Mutex
    errCh := make(chan error, len(f.Workers))

    for _, worker := range f.Workers {{
        wg.Add(1)
        go func(w *ParallelWorker) {{
            defer wg.Done()
            result, err := w.Run(ctx, query)
            if err != nil {{
                errCh <- fmt.Errorf("worker %s: %w", w.Name(), err)
                return
            }}
            mu.Lock()
            results[w.Name()] = result
            mu.Unlock()
        }}(worker)
    }}

    wg.Wait()
    close(errCh)

    if errs := collectErrors(errCh); len(errs) > 0 {{
        return results, fmt.Errorf("partial failure: %v", errs)
    }}

    slog.Info("fan_out complete", "results", len(results))
    return results, nil
}}

func collectErrors(ch <-chan error) []error {{
    var errs []error
    for e := range ch {{
        errs = append(errs, e)
    }}
    return errs
}}"""

    entrypoint = f"""func main() {{
    ctx := context.Background()

    fanOut := New{safe_name.title()}FanOut()
    results, err := fanOut.Run(ctx, "Search for recent developments in AI")
    if err != nil {{
        slog.Error("fan_out partial failure", "error", err)
    }}

    fmt.Println("Parallel fan-out completed")
    for worker, result := range results {{
        fmt.Printf("  %s: %s\\n", worker, result[:60])
    }}
}}"""

    return {"imports": imports, "agents": agents, "tools": tools, "workflow": workflow, "entrypoint": entrypoint}


GO_GENERATORS = {
    "graph": generate_go_graph,
    "dynamic": generate_go_dynamic,
    "collaborative": generate_go_collaborative,
    "template-seq": generate_go_template_sequential,
    "template-parallel": generate_go_template_parallel,
}


TS_TEMPLATE = """// {name} — {wf_type} workflow
// Generated by adk-agentic-prod-workflows

{imports}

// ── Agent definitions ─────────────────────────────────────────────

{agents}

// ── Tool definitions ──────────────────────────────────────────────

{tools}

// ── Workflow assembly ─────────────────────────────────────────────

{workflow}

// ── Entrypoint ────────────────────────────────────────────────────

{entrypoint}
"""


def generate_ts_graph(name: str) -> dict:
    safe_name = name.replace("-", "_")
    imports = """import { Agent, GraphAgent, type Node, type Edge } from '@google/adk';
import { FunctionTool } from '@google/adk/tools';
import { z } from 'zod';"""

    agents = f"""const ValidateInput = z.object({{
  query: z.string().describe('User query to validate'),
}});

async function validateInput(params: z.infer<typeof ValidateInput>) {{
  console.log('validate_input', {{ query_length: params.query.length }});
  if (params.query.length < 3) {{
    return {{ is_valid: false, sanitized_query: '', reason: 'Query too short' }};
  }}
  return {{ is_valid: true, sanitized_query: params.query.trim(), reason: null }};
}}

const validatorAgent = new Agent({{
  name: '{safe_name}_validator',
  model: 'gemini-2.5-flash',
  instruction: 'Validate and sanitize user input before processing.',
  tools: [new FunctionTool(validateInput, {{ schema: ValidateInput }})],
}});

const processorAgent = new Agent({{
  name: '{safe_name}_processor',
  model: 'gemini-2.5-flash',
  instruction: 'Process validated queries and return structured results.',
  tools: [],
}});"""

    tools = """// Tool definitions for the workflow
// Add custom tools here using FunctionTool with Zod schemas"""

    workflow = f"""const workflow = new GraphAgent({{
  name: '{safe_name}_graph',
  nodes: [
    {{ id: 'validate', agent: validatorAgent }},
    {{ id: 'process', agent: processorAgent }},
  ],
  edges: [
    {{
      source: 'validate',
      target: 'process',
      condition: (state) => state.is_valid === true,
    }},
  ],
  entryPoint: 'validate',
}});"""

    entrypoint = """// Run: npx tsx index.ts
async function main() {
  const result = await workflow.run({ query: 'Test query' });
  console.log('Result:', result);
}

main().catch(console.error);"""

    return {"imports": imports, "agents": agents, "tools": tools, "workflow": workflow, "entrypoint": entrypoint}


def generate_ts_agent_server(name: str) -> dict:
    safe_name = name.replace("-", "_")
    imports = """import { Agent, A2AServer, type AgentCard } from '@google/adk';
import { FunctionTool } from '@google/adk/tools';
import { z } from 'zod';
import express from 'express';"""

    agents = f"""const SearchInput = z.object({{
  query: z.string().describe('Search query'),
}});

async function searchKnowledgeBase(params: z.infer<typeof SearchInput>) {{
  console.log('search_kb', {{ query: params.query }});
  return {{ results: [], count: 0 }};
}}

const mainAgent = new Agent({{
  name: '{safe_name}_agent',
  model: 'gemini-2.5-flash',
  instruction: 'You are a production agent server. Handle requests using available tools.',
  tools: [new FunctionTool(searchKnowledgeBase, {{ schema: SearchInput }})],
}});"""

    tools = """// Auth middleware for Firebase and OAuth2 tokens
async function verifyAuth(req: express.Request, res: express.Response, next: express.NextFunction) {
  const authHeader = req.headers.authorization;
  if (!authHeader?.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Missing or invalid Authorization header' });
  }
  const token = authHeader.slice(7);
  try {
    // Verify Firebase token or OAuth2 JWT
    // const decoded = await admin.auth().verifyIdToken(token);
    // req.user = decoded;
    next();
  } catch (error) {
    return res.status(401).json({ error: 'Invalid token' });
  }
}"""

    workflow = f"""const agentCard: AgentCard = {{
  name: '{name}',
  description: 'Production ADK agent server',
  url: process.env.AGENT_URL || 'http://localhost:8080',
  capabilities: {{ streaming: true, a2a: true }},
  authScheme: 'bearer_token',
}};

const server = new A2AServer({{
  agent: mainAgent,
  card: agentCard,
  transport: 'sse',
}});"""

    entrypoint = """const app = express();
app.use(express.json());
app.use('/health', (_, res) => res.json({ status: 'ok' }));

async function main() {
  await server.start(app);
  const port = process.env.PORT || 8080;
  app.listen(port, () => {
    console.log(`Agent server running on port ${port}`);
  });
}

main().catch(console.error);"""

    return {"imports": imports, "agents": agents, "tools": tools, "workflow": workflow, "entrypoint": entrypoint}


TS_GENERATORS = {
    "graph": generate_ts_graph,
    "agent-server": generate_ts_agent_server,
}


def scaffold_python(name: str, wf_type: str, target_dir: Path) -> None:
    generator = PYTHON_GENERATORS.get(wf_type)
    if not generator:
        print(f"Error: Python does not support workflow type '{wf_type}'")
        print(f"Supported types: {list(PYTHON_GENERATORS.keys())}")
        sys.exit(1)

    parts = generator(name)
    content = PYTHON_TEMPLATE.format(name=name, wf_type=WORKFLOW_TYPES[wf_type], **parts)

    target_dir.mkdir(parents=True, exist_ok=True)
    workflow_file = target_dir / "workflow.py"
    workflow_file.write_text(content)

    init_file = target_dir / "__init__.py"
    init_file.write_text(f"# {name} — {wf_type} workflow\n")

    print(f"  Created: {workflow_file}")
    print(f"  Created: {init_file}")


def scaffold_go(name: str, wf_type: str, target_dir: Path) -> None:
    generator = GO_GENERATORS.get(wf_type)
    if not generator:
        print(f"Error: Go does not support workflow type '{wf_type}'")
        print(f"Supported types: {list(GO_GENERATORS.keys())}")
        sys.exit(1)

    parts = generator(name)
    content = GO_TEMPLATE.format(name=name, wf_type=WORKFLOW_TYPES[wf_type], **parts)

    target_dir.mkdir(parents=True, exist_ok=True)
    main_file = target_dir / "main.go"
    main_file.write_text(content)

    go_mod = target_dir / "go.mod"
    safe_name = name.replace("-", "_")
    go_mod.write_text(f"""module github.com/${{YOUR_GITHUB_USERNAME}}/{name}

go 1.23

require (
    google.golang.org/adk v0.0.0
    google.golang.org/genai v0.0.0
)
""")

    print(f"  Created: {main_file}")
    print(f"  Created: {go_mod}")


def scaffold_ts(name: str, wf_type: str, target_dir: Path) -> None:
    generator = TS_GENERATORS.get(wf_type)
    if not generator:
        print(f"Error: TS does not support workflow type '{wf_type}'")
        print(f"Supported types: {list(TS_GENERATORS.keys())}")
        sys.exit(1)

    parts = generator(name)
    content = TS_TEMPLATE.format(name=name, wf_type=WORKFLOW_TYPES.get(wf_type, wf_type), **parts)

    target_dir.mkdir(parents=True, exist_ok=True)
    index_file = target_dir / "index.ts"
    index_file.write_text(content)

    package_json = target_dir / "package.json"
    package_json.write_text(f"""{{
  "name": "{name}",
  "version": "1.0.0",
  "description": "{WORKFLOW_TYPES.get(wf_type, wf_type)} workflow — generated by adk-agentic-prod-workflows",
  "type": "module",
  "scripts": {{
    "build": "tsc",
    "start": "tsx index.ts",
    "typecheck": "tsc --noEmit"
  }},
  "dependencies": {{
    "@google/adk": "^1.0.0",
    "express": "^4.21.0",
    "zod": "^3.23.0"
  }},
  "devDependencies": {{
    "@types/express": "^5.0.0",
    "@types/node": "^22.0.0",
    "tsx": "^4.19.0",
    "typescript": "^5.6.0"
  }}
}}
""")

    tsconfig = target_dir / "tsconfig.json"
    tsconfig.write_text("""{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "lib": ["ES2022"],
    "outDir": "./dist",
    "rootDir": ".",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "declaration": true,
    "sourceMap": true
  },
  "include": ["*.ts"],
  "exclude": ["node_modules", "dist"]
}
""")

    print(f"  Created: {index_file}")
    print(f"  Created: {package_json}")
    print(f"  Created: {tsconfig}")


def scaffold_project(name: str, wf_type: str, lang: str, output_dir: str | None = None,
                     with_mcp: bool = False, with_memory: bool = False,
                     with_model_armor: bool = False) -> Path:
    base = Path(output_dir) if output_dir else Path.cwd()
    project_dir = base / name

    if project_dir.exists():
        print(f"Error: Directory '{project_dir}' already exists")
        sys.exit(1)

    print(f"\nScaffolding {wf_type} workflow '{name}' ({lang})")
    print(f"  Target: {project_dir}")
    print(f"  Type: {WORKFLOW_TYPES.get(wf_type, wf_type)}")
    if with_mcp:
        print(f"  MCP: enabled (MCP server scaffolding)")
    if with_memory:
        print(f"  Memory: enabled (SessionService configuration)")
    if with_model_armor:
        print(f"  Model Armor: enabled (double-shield content safety)")

    # Create directory structure
    dirs = [
        project_dir / "app",
        project_dir / "tests",
        project_dir / "evals",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)

    # Create language-specific source
    if lang == "python":
        scaffold_python(name, wf_type, project_dir / "app")
        tests_init = project_dir / "tests" / "__init__.py"
        tests_init.write_text(f"# Tests for {name}\n")
    elif lang == "go":
        scaffold_go(name, wf_type, project_dir)
    elif lang == "ts":
        scaffold_ts(name, wf_type, project_dir)

    # Create shared files
    _write_shared_files(project_dir, name, wf_type, lang)

    # MCP scaffolding
    if with_mcp:
        mcp_dir = project_dir / "mcp_servers"
        mcp_dir.mkdir(parents=True, exist_ok=True)
        (mcp_dir / "__init__.py").write_text("# MCP tool servers\n")
        (mcp_dir / "example_server.py").write_text('''"""Example MCP server using FastMCP."""
from mcp.server.fastmcp import FastMCP

mcp = FastMCP("Example MCP Server")

@mcp.tool()
def query_database(query: str) -> dict:
    """Execute a read-only database query."""
    return {"status": "ok", "data": [], "query": query}

@mcp.tool()
def get_resource(id: str) -> dict:
    """Fetch a resource by ID."""
    return {"id": id, "status": "ok"}

if __name__ == "__main__":
    mcp.run(transport="stdio")
''')
        print(f"  Created: {mcp_dir / 'example_server.py'}")

    # Memory configuration
    if with_memory:
        memory_file = project_dir / "app" / "memory_config.py"
        memory_file.write_text('''"""Memory and session configuration."""
import os
from google.adk.sessions import InMemorySessionService

# Development: in-memory sessions (not persistent across restarts)
# Production: FirestoreSessionService or SpannerSessionService
SESSION_SERVICE = InMemorySessionService()

# Memory hierarchy:
# L1: session.state (working memory within a session)
# L2: SessionService (session persistence across restarts)
# L3: Persistent store (user profiles, preferences across sessions)
# L4: Episodic archive (full conversation history, analytics)
''')
        print(f"  Created: {memory_file}")

    # Model Armor scaffolding
    if with_model_armor:
        security_dir = project_dir / "app" / "security"
        security_dir.mkdir(parents=True, exist_ok=True)
        (security_dir / "__init__.py").write_text("# Security module: Model Armor + Content Safety\n")

        model_armor_file = security_dir / "model_armor.py"
        model_armor_file.write_text('''"""Model Armor client — Google content safety with double-shield pattern.

Provides input sanitization (before agent) and output sanitization (after agent).
Quota formula: (peak_users * avg_turns_per_session) * 2 + 25%
"""

import os
import time
import httpx
from dataclasses import dataclass, field
from typing import Any


@dataclass
class SafetyResult:
    passed: bool
    flagged: bool = False
    reason: str | None = None
    sanitized_text: str | None = None
    latency_ms: float = 0.0


class ModelArmorClient:
    """REST API wrapper for Google Model Armor content safety."""

    def __init__(
        self,
        project_id: str | None = None,
        location: str = "us-central1",
        template_name: str = "strict",
    ):
        self.project_id = project_id or os.getenv("GOOGLE_CLOUD_PROJECT")
        self.location = location
        self.template_name = template_name
        self._client = httpx.AsyncClient(timeout=30.0)

    async def sanitize_input(self, text: str, user_id: str = "") -> SafetyResult:
        """Pre-model safety check on user input."""
        start = time.monotonic()
        try:
            resp = await self._client.post(
                f"https://modelarmor.{self.location}.googleapis.com/v1/"
                f"projects/{self.project_id}/locations/{self.location}/"
                f"templates/{self.template_name}:sanitize",
                json={"text": text, "user_id": user_id},
            )
            data = resp.json()
            return SafetyResult(
                passed=not data.get("blocked", False),
                flagged=data.get("blocked", False),
                reason=data.get("blockReason"),
                sanitized_text=data.get("sanitizedText", text),
                latency_ms=(time.monotonic() - start) * 1000,
            )
        except Exception as e:
            # Fail closed: block on error
            return SafetyResult(
                passed=False, flagged=True, reason=f"Model Armor error: {e}",
                latency_ms=(time.monotonic() - start) * 1000,
            )

    async def sanitize_output(self, text: str) -> SafetyResult:
        """Post-model safety check on agent output."""
        start = time.monotonic()
        try:
            resp = await self._client.post(
                f"https://modelarmor.{self.location}.googleapis.com/v1/"
                f"projects/{self.project_id}/locations/{self.location}/"
                f"templates/{self.template_name}:sanitize",
                json={"text": text},
            )
            data = resp.json()
            return SafetyResult(
                passed=not data.get("blocked", False),
                flagged=data.get("blocked", False),
                sanitized_text=data.get("sanitizedText", text),
                latency_ms=(time.monotonic() - start) * 1000,
            )
        except Exception as e:
            return SafetyResult(
                passed=False, flagged=True, reason=f"Model Armor error: {e}",
                latency_ms=(time.monotonic() - start) * 1000,
            )


# Double-shield callbacks for agent wiring
async def input_safety_guardrail(callback_context):
    """Before-agent callback: sanitize user input via Model Armor."""
    client = ModelArmorClient()
    user_input = callback_context.state.get("user_input", "")
    result = await client.sanitize_input(user_input)
    if result.flagged:
        callback_context.state["safety_blocked"] = True
        callback_context.state["safety_reason"] = result.reason
    else:
        callback_context.state["safety_blocked"] = False
        callback_context.state["sanitized_input"] = result.sanitized_text


async def output_safety_guardrail(callback_context):
    """After-agent callback: sanitize model output via Model Armor."""
    client = ModelArmorClient()
    model_output = callback_context.state.get("model_output", "")
    result = await client.sanitize_output(model_output)
    if result.flagged:
        callback_context.state["output_blocked"] = True
        callback_context.state["output_reason"] = result.reason
    else:
        callback_context.state["output_blocked"] = False
        callback_context.state["safe_output"] = result.sanitized_text
''')
        print(f"  Created: {model_armor_file}")

        # Template JSON configs (Minimal, Standard, Strict)
        configs_dir = security_dir / "model_armor_configs"
        configs_dir.mkdir(parents=True, exist_ok=True)

        (configs_dir / "minimal.json").write_text("""{
  "name": "minimal",
  "description": "Minimal Model Armor config — blocks only the most severe violations.",
  "settings": {
    "harassment": "BLOCK_ONLY_HIGH",
    "hate_speech": "BLOCK_ONLY_HIGH",
    "sexually_explicit": "BLOCK_ONLY_HIGH",
    "dangerous": "BLOCK_ONLY_HIGH",
    "floor_setting": "BLOCK_ONLY_HIGH"
  }
}
""")
        (configs_dir / "standard.json").write_text("""{
  "name": "standard",
  "description": "Standard Model Armor config — balances safety and throughput.",
  "settings": {
    "harassment": "BLOCK_MEDIUM_AND_ABOVE",
    "hate_speech": "BLOCK_MEDIUM_AND_ABOVE",
    "sexually_explicit": "BLOCK_MEDIUM_AND_ABOVE",
    "dangerous": "BLOCK_MEDIUM_AND_ABOVE",
    "floor_setting": "BLOCK_MEDIUM_AND_ABOVE"
  }
}
""")
        (configs_dir / "strict.json").write_text("""{
  "name": "strict",
  "description": "Strict Model Armor config — maximum safety for regulated domains.",
  "settings": {
    "harassment": "BLOCK_LOW_AND_ABOVE",
    "hate_speech": "BLOCK_LOW_AND_ABOVE",
    "sexually_explicit": "BLOCK_LOW_AND_ABOVE",
    "dangerous": "BLOCK_LOW_AND_ABOVE",
    "floor_setting": "BLOCK_LOW_AND_ABOVE"
  }
}
""")
        print(f"  Created: {configs_dir}/minimal.json")
        print(f"  Created: {configs_dir}/standard.json")
        print(f"  Created: {configs_dir}/strict.json")

    print(f"\nDone! Project scaffolded at {project_dir}")
    if lang == "python":
        print(f"  Next: cd {name} && pip install -r requirements.txt")
    elif lang == "go":
        print(f"  Next: cd {name} && go mod tidy && go run .")
    elif lang == "ts":
        print(f"  Next: cd {name} && npm install && npm start")
    return project_dir


def _write_shared_files(project_dir: Path, name: str, wf_type: str, lang: str) -> None:
    reqs = project_dir / "requirements.txt"
    reqs.write_text("google-adk>=1.0.0\nstructlog>=24.0.0\npydantic>=2.0.0\n")

    gitignore = project_dir / ".gitignore"
    gitignore.write_text("""__pycache__/
*.pyc
.env
.venv/
venv/
dist/
*.egg-info/
.DS_Store
""")

    env_example = project_dir / ".env.example"
    env_example.write_text("""GOOGLE_API_KEY=your-api-key
GOOGLE_CLOUD_PROJECT=your-project-id
LOG_LEVEL=INFO
""")

    readme = project_dir / "README.md"
    readme.write_text(f"""# {name}

{WORKFLOW_TYPES[wf_type]}

Generated by adk-agentic-prod-workflows.

## Structure

```
{name}/
├── app/              # Workflow source
├── tests/            # Unit tests
├── evals/            # Evaluation harness
├── requirements.txt  # Python dependencies
└── .env.example      # Environment template
```

## Quick Start

```bash
pip install -r requirements.txt
cp .env.example .env  # edit with your keys
python app/workflow.py
```
""")


def main():
    all_wf_types = list(WORKFLOW_TYPES.keys())
    # TS has its own types
    ts_types = list(TS_GENERATORS.keys())

    parser = argparse.ArgumentParser(
        description="Scaffold a new ADK agentic workflow project",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Examples:\n"
               "  python init_adk_workflow.py --type graph --lang python --name my-flow\n"
               "  python init_adk_workflow.py --type collaborative --lang python --name support-triage\n"
               "  python init_adk_workflow.py --type dynamic --lang go --name order-pipeline\n"
               "  python init_adk_workflow.py --type graph --lang ts --name ts-workflow\n"
               "  python init_adk_workflow.py --type agent-server --lang ts --name my-server\n"
               "  python init_adk_workflow.py --type template-loop --lang python --name refinement-loop --with-mcp",
    )
    parser.add_argument(
        "--type", required=True,
        choices=all_wf_types + ts_types,
        help="Workflow type"
    )
    parser.add_argument(
        "--lang", required=True,
        choices=["python", "go", "ts"],
        help="Programming language"
    )
    parser.add_argument(
        "--name", required=True,
        help="Project/package name (kebab-case recommended)"
    )
    parser.add_argument(
        "--output-dir",
        help="Parent directory for the project (default: current directory)"
    )
    parser.add_argument(
        "--with-mcp", action="store_true",
        help="Add MCP server scaffolding and tool examples"
    )
    parser.add_argument(
        "--with-memory", action="store_true",
        help="Add SessionService configuration and memory hierarchy setup"
    )
    parser.add_argument(
        "--with-model-armor", action="store_true",
        help="Add Model Armor content safety: double-shield runner, template configs, security plugin"
    )

    args = parser.parse_args()

    # Validate type/language combinations
    if args.lang == "go" and args.type not in GO_GENERATORS:
        print(f"Error: Go does not support '{args.type}' workflow type")
        print(f"  Go supported types: {list(GO_GENERATORS.keys())}")
        sys.exit(1)

    if args.lang == "ts" and args.type not in TS_GENERATORS:
        print(f"Error: TypeScript does not support '{args.type}' workflow type")
        print(f"  TS supported types: {list(TS_GENERATORS.keys())}")
        sys.exit(1)

    scaffold_project(args.name, args.type, args.lang, args.output_dir,
                     with_mcp=args.with_mcp, with_memory=args.with_memory,
                     with_model_armor=args.with_model_armor)


if __name__ == "__main__":
    main()
